apiVersion: v1
kind: Namespace
metadata:
  name: auth-services
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
      - name: auth
        image: ishansingl.azurecr.io/auth-service:latest
        env:
        - name: DATABASE_URL
          value: "postgresql://bfh_owner:dm9qYk5odUhBOVIx@postgres:5432/bfh_auth"
        - name: REDIS_HOST
          value: redis
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: REDIS_PASSWORD
        ports:
        - containerPort: 3000

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-services
spec:
  selector:
    app: auth
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000